my-portfolio: mobile version: milestone-2
Debas-31/my-portfolio pull request #2
Opened 2021-08-18 22:27 UTC by Debas-31

# My-portfolio mobile version project continuation of a milestone-1
- Added work-section
- Added README about the section

2021-08-18 22:55 UTC, barackm requested changes
Hi @Debas-31, 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-18 22:55 UTC, barackm commented on index.html
> +            </div>
- [ ] I think the social media icons are actually links, so they should be inside a `<ul>` tag, this is because it will be a list of icons, something like this: 
```
<ul>
   <li>
       <a href="https://"><i class="fab fa-github fa-2x"></i></a>
   </li>
</ul>
```

Let us fix this please 😉

2021-08-18 22:55 UTC, barackm commented on index.html
> +                    <h2>Multi-Post Stories</h2>
- [ ] Kindly let us align the work title `<h2>` to the left instead of the center as it is in the Figma design

2021-08-18 22:55 UTC, barackm commented on index.html
> +                      <h2>Multi-Post Stories</h2>
- [ ] Kindly let us align the work title <h2> to the left instead of the center as it is in the Figma design
- [ ] Let us do the same thing for all the other titles in this section please 👍

2021-08-19 07:13 UTC, Emmyn5600 commented on index.html
> +                    <h2>Multi-Post Stories</h2>
Well solved

2021-08-19 07:13 UTC, Emmyn5600 commented on index.html
> +                      <h2>Multi-Post Stories</h2>
Well done

2021-08-19 07:13 UTC, Emmyn5600 commented on index.html
> +            </div>
Well done

2021-08-19 07:14 UTC, Emmyn5600 approved these changes
Hi, 

Good job so far! 👏🏼 @Debas-31 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-20 13:43 UTC, merged